package com.mathsquest.app.ui.components

import android.provider.Settings
import androidx.annotation.DrawableRes
import androidx.compose.animation.core.FastOutSlowInEasing
import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.mathsquest.app.R

/** Leo's expressions. Drawables are generated by tools/leo/make_vectors.py. */
enum class LeoFace(@DrawableRes val res: Int, val description: String) {
    Happy(R.drawable.leo_happy, "Leo the lion smiling and holding a Gold Coin"),
    Focused(R.drawable.leo_focused, "Leo the lion concentrating, pencil ready"),
    Thinking(R.drawable.leo_thinking, "Leo the lion thinking, paw on his chin"),
    Cheering(R.drawable.leo_cheering, "Leo the lion cheering with both paws up"),
    Proud(R.drawable.leo_proud, "Leo the lion with star eyes, holding a trophy"),
    Hopeful(R.drawable.leo_hopeful, "Leo the lion looking hopeful, paws clasped"),
    Excited(R.drawable.leo_excited, "Leo the lion, excited and holding a calendar"),
    Sleepy(R.drawable.leo_sleepy, "Leo the lion, sleepy and yawning"),
    Coach(R.drawable.leo_coach, "Leo the lion winking with a thumbs-up, holding a bar chart"),
    Waving(R.drawable.leo_waving, "Leo the lion waving hello"),
    Pointing(R.drawable.leo_pointing, "Leo the lion pointing at the list"),
    Ready(R.drawable.leo_ready, "Leo the lion with a fist pump, ready to go"),
    Welcome(R.drawable.leo_welcome, "Leo the lion with his arms open wide"),
    Covering(R.drawable.leo_covering, "Leo the lion covering his eyes so he cannot see the PIN"),
    Reporter(R.drawable.leo_reporter, "Leo the lion wearing reading glasses and holding a clipboard"),
}

/** Leo gently bobs unless [bob] is false or the device has animations turned off. */
@Composable
fun Leo(face: LeoFace, size: Dp, modifier: Modifier = Modifier, bob: Boolean = true) {
    val context = LocalContext.current
    val animationsOn = remember {
        Settings.Global.getFloat(context.contentResolver, Settings.Global.ANIMATOR_DURATION_SCALE, 1f) > 0f
    }
    val offsetPx = with(LocalDensity.current) { 5.dp.toPx() }
    val dy = if (bob && animationsOn) {
        val t = rememberInfiniteTransition(label = "leo-bob")
        val v by t.animateFloat(
            initialValue = 0f,
            targetValue = -offsetPx,
            animationSpec = infiniteRepeatable(tween(1300, easing = FastOutSlowInEasing), RepeatMode.Reverse),
            label = "leo-bob-y",
        )
        v
    } else {
        0f
    }
    Image(
        painter = painterResource(face.res),
        contentDescription = face.description,
        modifier = modifier
            .size(size)
            .graphicsLayer { translationY = dy },
    )
}
