package com.mathsquest.app.sound

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import androidx.annotation.RawRes
import com.mathsquest.app.R
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import javax.inject.Inject
import javax.inject.Singleton

/** Short game sounds (generated by tools/sfx/make_sounds.py). Children can turn them off on the home screen. */
@Singleton
class SoundPlayer @Inject constructor(@ApplicationContext context: Context) {

    enum class Sfx(@RawRes val res: Int, val volume: Float) {
        TAP(R.raw.sfx_tap, 0.35f),
        DROP(R.raw.sfx_drop, 0.75f),
        CORRECT(R.raw.sfx_correct, 0.8f),
        COIN(R.raw.sfx_coin, 0.7f),
        WRONG(R.raw.sfx_wrong, 0.6f),
        LEVEL_UP(R.raw.sfx_levelup, 0.85f),
        COMPLETE(R.raw.sfx_complete, 0.8f),
    }

    private val prefs = context.getSharedPreferences("settings", Context.MODE_PRIVATE)
    private val _enabled = MutableStateFlow(prefs.getBoolean(KEY_SOUND, true))
    val enabled: StateFlow<Boolean> = _enabled.asStateFlow()

    private val pool: SoundPool = SoundPool.Builder()
        .setMaxStreams(4)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build(),
        )
        .build()

    private val ids: Map<Sfx, Int> = Sfx.entries.associateWith { pool.load(context, it.res, 1) }

    fun play(sfx: Sfx) {
        if (!_enabled.value) return
        val id = ids[sfx] ?: return
        pool.play(id, sfx.volume, sfx.volume, 1, 0, 1f)
    }

    fun setEnabled(on: Boolean) {
        _enabled.value = on
        prefs.edit().putBoolean(KEY_SOUND, on).apply()
    }

    private companion object {
        const val KEY_SOUND = "sound_on"
    }
}
