"""Converts Leo's SVG expressions (leo_faces.py) into Android vector drawables.

Usage: python3 tools/leo/make_vectors.py   (run from the repo root)
Writes app/src/main/res/drawable/leo_<face>.xml for every face.
"""
import os, re, sys
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.dirname(__file__))
from leo_faces import BASE_TOP, FACES  # noqa: E402

PAD = 8          # Leo's props poke outside the 120x120 box; pad the viewport
SIZE = 120 + 2 * PAD
OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'app', 'src', 'main', 'res', 'drawable')
ANDROID = 'http://schemas.android.com/apk/res/android'


def ellipse_path(cx, cy, rx, ry):
    return (f'M{cx - rx:.2f},{cy:.2f} a{rx:.2f},{ry:.2f} 0 1,0 {2 * rx:.2f},0 '
            f'a{rx:.2f},{ry:.2f} 0 1,0 {-2 * rx:.2f},0 z')


def rect_path(x, y, w, h, r):
    if r <= 0:
        return f'M{x},{y} h{w} v{h} h{-w} z'
    r = min(r, w / 2, h / 2)
    return (f'M{x + r},{y} h{w - 2 * r} a{r},{r} 0 0,1 {r},{r} v{h - 2 * r} a{r},{r} 0 0,1 {-r},{r} '
            f'h{-(w - 2 * r)} a{r},{r} 0 0,1 {-r},{-r} v{-(h - 2 * r)} a{r},{r} 0 0,1 {r},{-r} z')


def color(c):
    if c is None or c == 'none':
        return None
    c = c.strip()
    if re.fullmatch(r'#[0-9A-Fa-f]{6}', c):
        return '#FF' + c[1:].upper()
    raise ValueError('unsupported colour ' + c)


def rotate_attrs(t):
    m = re.fullmatch(r'\s*rotate\(\s*([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)\s*\)\s*', t or '')
    return (float(m.group(1)), float(m.group(2)), float(m.group(3))) if m else None


def emit(el, out, ind):
    tag = el.tag
    a = el.attrib
    if tag == 'g':
        rot = rotate_attrs(a.get('transform'))
        out.append(f'{ind}<group android:rotation="{rot[0]}" android:pivotX="{rot[1]}" android:pivotY="{rot[2]}">')
        for ch in el:
            emit(ch, out, ind + '    ')
        out.append(f'{ind}</group>')
        return
    f = lambda k, d=0.0: float(a.get(k, d))
    if tag == 'circle':
        d = ellipse_path(f('cx'), f('cy'), f('r'), f('r'))
    elif tag == 'ellipse':
        d = ellipse_path(f('cx'), f('cy'), f('rx'), f('ry'))
    elif tag == 'rect':
        d = rect_path(f('x'), f('y'), f('width'), f('height'), f('rx'))
    elif tag == 'path':
        d = a['d']
    else:
        raise ValueError('unsupported element ' + tag)
    attrs = [f'android:pathData="{d}"']
    fill = color(a.get('fill', '#000000'))
    if fill:
        attrs.append(f'android:fillColor="{fill}"')
    stroke = color(a.get('stroke'))
    if stroke:
        attrs.append(f'android:strokeColor="{stroke}"')
        attrs.append(f'android:strokeWidth="{a.get("stroke-width", "1")}"')
        if a.get('stroke-linecap'):
            attrs.append(f'android:strokeLineCap="{a["stroke-linecap"]}"')
        if a.get('stroke-linejoin'):
            attrs.append(f'android:strokeLineJoin="{a["stroke-linejoin"]}"')
    if a.get('opacity'):
        attrs.append(f'android:fillAlpha="{a["opacity"]}"')
    rot = rotate_attrs(a.get('transform'))
    line = f'{ind}<path ' + ' '.join(attrs) + ' />'
    if rot:
        out.append(f'{ind}<group android:rotation="{rot[0]}" android:pivotX="{rot[1]}" android:pivotY="{rot[2]}">')
        out.append('    ' + line)
        out.append(f'{ind}</group>')
    else:
        out.append(line)


def build(face):
    root = ET.fromstring('<svg>' + BASE_TOP + FACES[face] + '</svg>')
    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f'<!-- Generated by tools/leo/make_vectors.py from leo_faces.py ("{face}"). Do not edit by hand. -->',
        f'<vector xmlns:android="{ANDROID}"',
        f'    android:width="{SIZE}dp" android:height="{SIZE}dp"',
        f'    android:viewportWidth="{SIZE}" android:viewportHeight="{SIZE}">',
        f'    <group android:translateX="{PAD}" android:translateY="{PAD}">',
    ]
    for el in root:
        emit(el, out, '        ')
    out += ['    </group>', '</vector>', '']
    return '\n'.join(out)


if __name__ == '__main__':
    os.makedirs(OUT, exist_ok=True)
    for face in FACES:
        with open(os.path.join(OUT, f'leo_{face}.xml'), 'w') as fh:
            fh.write(build(face))
    print('wrote', len(FACES), 'drawables:', ', '.join(sorted(FACES)))
